name: "Mercor"

web: "https://github.com/shprink/mercor"

description: "A lightweight UI Library for Mootools"

license: "MIT"

copyright: "&copy; 2012 Julien Renaux"

authors: "Julien Renaux <contact@julienrenaux.fr>"

version: "1.0"

sources:
  - "Source/UI/Mercor.js"
  - "Source/UI/Mercor.Element.js"
  - "Source/UI/Mercor.Alert.js"
  - "Source/UI/Mercor.Modal.js"
  - "Source/UI/Mercor.Slideshow.js"
  - "Source/UI/Mercor.Tab.js"
  - "Source/UI/Mercor.Tip.js"
  - "Source/Behaviors/Behavior.js"
  - "Source/Behaviors/Mercor.Alert.js"
  - "Source/Behaviors/Mercor.Modal.js"
  - "Source/Behaviors/Mercor.Slideshow.js"
  - "Source/Behaviors/Mercor.Tab.js"
  - "Source/Behaviors/Mercor.Tip.js"
  - "Source/Mootools/Core.js"
  - "Source/Mootools/More.js"
